### ISSUE TITLE
No Javascript API?

### ISSUE THREAD

**Issue by batjko** [ovhemert/pino-papertrail#11]
I'm wondering if this library is meant to be used inside of a Node project as well. Is there a chance of an exported API to use in my code, like most others transports?

**Comment by ovhemert** [comment]
At the moment, you can only use the library from the CLI.

I would also like to have the API support like I've done with [pino-stackdriver](https://github.com/ovhemert/pino-stackdriver), but my time is limited. If you want to give it a shot, be my guest.

**Comment by ovhemert** [comment]
API added in v1.2.0
