### ISSUE TITLE
I am getting a pino-papertrail not recognized

### ISSUE THREAD

**Issue by katlimruiz** [ovhemert/pino-papertrail#17]
Do you need to do an `npm link pino-papertrail` so it can be called after the pipe?

If so, how would you do this in a docker container?

**Comment by ovhemert** [comment]
Did you install with the `-g` flag?

```sh
$ npm install --production -g pino-papertrail
````

Then you should be able to call `pino-papertrail` from a terminal and not get the error.

**Comment by katlimruiz** [comment]
well RUN `npm link pino-papertrail` also worked, but your solution is better.

It seems "weird" first to add one more package at deploy time, but I guess it makes sense since you want to decide where to log up until the last step, and also leave it open to select another one later if needed.
